version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - .dockerconfig/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php
      # - oracle
    ports:
      - 1112:80

  php:
    build: .dockerconfig/php
    volumes:
      # - .dockerconfig/php/conf.d:/user/local/etc/php/conf.d
      - .:/var/www/html
    expose:
      - 9000

  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    restart: unless-stopped
    ports:
        - 32122:1521
    volumes:
      - ./oracle-data:/ORCL

    

  
   